nearteam_user:
    pattern: /
    defaults: { _controller: NearteamUserBundle:User:searchUser }
nearteam_user:
    pattern: /search_user
    defaults: { _controller: NearteamUserBundle:User:searchUser }
nearteam_user_viewgrid_user:
    pattern: /user_list
    defaults: { _controller: NearteamUserBundle:User:userList }
nearteam_user_ajax_form_search:
    pattern: /formSearch
    defaults: { _controller: NearteamUserBundle:User:formSearch }
nearteam_user_infos:
    pattern: /infos_user/{idUser}/{type}
    defaults: { _controller: NearteamUserBundle:User:getInfosUser }
nearteam_user_edit_user:
    pattern: /edit_user/{idUser}
    defaults: { _controller: NearteamUserBundle:User:saveUserEdit }
nearteam_user_changePassword_user:
    pattern: /changePassword
    defaults: { _controller: NearteamUserBundle:User:changePassword }	
nearteam_user_blacklist_user:
    pattern: /blacklist_user/{idUser}
    defaults: { _controller: NearteamUserBundle:User:blacklistUser }
    requirements:
        idUser:  \d+
nearteam_user_delete_user:
    pattern: /delete_user/{idUser}
    defaults: { _controller: NearteamUserBundle:User:deleteUser }
    requirements:
        idUser:  \d+